-- Query 1------;

SELECT  F_NAME, L_NAME from EMPLOYEES WHERE ADDRESS LIKE '%Elgin,IL%' ;

-- Query 2------;

SELECT  F_NAME, L_NAME from EMPLOYEES WHERE B_DATE  LIKE '%197%' ;

-- Query 3-----;

SELECT  F_NAME, L_NAME from EMPLOYEES WHERE DEP_ID= 5 AND  (SALARY BETWEEN  60000 AND  70000)   ;

-- Query 4A-----; 

SELECT * FROM EMPLOYEES ORDER BY DEP_ID;

-- Query 4B-----;

SELECT * FROM EMPLOYEES ORDER BY DEP_ID DESC , L_NAME DESC ;

-- Query 5A-----;
SELECT DEP_ID, COUNT(EMP_ID) FROM  EMPLOYEES GROUP BY DEP_ID;

-- Query 5B-----;

SELECT DEP_ID, COUNT(*), AVG(SALARY) FROM EMPLOYEES GROUP BY DEP_ID;

-- Query 5C-----;

SELECT DEP_ID, COUNT(*) AS  NUM_EMPLOYESS,  AVG(SALARY) AS AVERAGE_SALARY  FROM EMPLOYEES GROUP BY DEP_ID;

-- Query 5D----;

SELECT DEP_ID, COUNT(*) AS  NUM_EMPLOYESS,  AVG(SALARY) AS AVERAGE_SALARY  FROM EMPLOYEES GROUP BY DEP_ID ORDER BY AVERAGE_SALARY;

-- Query 5D----;

SELECT DEP_ID, COUNT(*) AS  NUM_EMPLOYESS,  AVG(SALARY) AS AVERAGE_SALARY  FROM EMPLOYEES GROUP BY DEP_ID  HAVING  COUNT(*) < 4  ORDER BY AVERAGE_SALARY;



